#!/bin/bash

# If the RUSTC is wrong, you could get a silent failure that is hard to troubleshoot.
if [[ "$CUSTOM_RUSTC" == "rustc"* ]]; then
  echo "CUSTOM_RUSTC is not set correctly. This should be a path to rustc binary, like: /home/.../rust-xtensa/build/x86_64-unknown-linux-gnu/stage2/bin/rustc"
  exit 1
fi

xargo build || exit 1

# change this for release flashes
BIN_PATH=target/xtensa-esp32-none-elf/debug/esp32

if [[ -e "$BIN_PATH" ]]; then
  rm $BIN_PATH.bin
fi

# convert to bin
esptool --chip esp32 elf2image --flash_mode="dio" --flash_freq "40m" --flash_size "4MB" -o $BIN_PATH.bin $BIN_PATH

# flash
esptool --chip esp32 --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 $BIN_PATH.bin
