#!/bin/bash


# change this to the directory of where you built rustc for xtensa
CUSTOM_RUSTC=/home/mabez/development/rust/xtensa/rust-xtensa

export RUST_BACKTRACE=1 
export XARGO_RUST_SRC=$CUSTOM_RUSTC/src 
export RUSTC=$CUSTOM_RUSTC/build/x86_64-unknown-linux-gnu/stage2/bin/rustc
