#!/bin/bash
# BASE=../rust/src
# RUSTC=../rust/build/x86_64-unknown-linux-gnu/stage2/bin/rustc

$RUSTC --crate-name core $XARGO_RUST_SRC/libcore/lib.rs --color always --crate-type lib --emit=asm,llvm-bc -C opt-level=3 -C codegen-units=1 -C debuginfo=2 -C metadata=3704b16aa5ea1124 -C extra-filename=-3704b16aa5ea1124 --out-dir target/xtensa/release/deps --target xtensa-esp32-none-elf
