#!/bin/bash

BASE=../rust/src
RUSTC=../rust/build/x86_64-unknown-linux-gnu/stage2/bin/rustc

$RUSTC --extern core=target/release/deps/xtensa-core.rlib --crate-name ___ src/main.rs --crate-type bin --emit=asm,llvm-bc -C opt-level=3 -C codegen-units=1 -C debuginfo=0 -C metadata=3704b16aa5ea1124 -C extra-filename=-3704b16aa5ea1124 --out-dir target/xtensa/release/deps --target xtensa
