#!/bin/bash

# problem:- the core crate is not using the passed rustflags, temp work around copy the output of -v, and add the correct emit flags for the core crate

CUSTOM_RUSTC=/home/mabez/development/rust/rust-xtensa/rust
# /home/mabez/development/rust/xargo/target/release/
CUSTOM_XARGO_PATH=xargo

# build the core
XARGO_RUST_SRC=$CUSTOM_RUSTC/src RUSTC=$CUSTOM_RUSTC/build/x86_64-unknown-linux-gnu/stage2/bin/rustc $CUSTOM_XARGO_PATH rustc --target xtensa --release --verbose -- --emit=asm --extern core=target/release/deps/xtensa-core.rlib
